Sound API
split-cube-studios/ardent pull request #43
Opened 2021-01-23 17:49 UTC by zacharyburkett

2021-02-05 10:35 UTC, svenwiltink requested changes

2021-02-05 10:35 UTC, svenwiltink commented on internal/ebiten/component.go
> +	sound := a.ToSound()
casting 4 times in a row, might as well do it directly

2021-02-05 10:35 UTC, svenwiltink commented on internal/ebiten/sound.go
> +type SoundControl struct {
Might be me not knowing the ebiten sound control, but adding some documentation as to what the key and value signify might be useful. The keys are the names of the volume groups, correct?

The reason `groups` is defined as a map of Sounds is so that they are indexed and can be removed easily I suppose?

2021-02-05 10:35 UTC, svenwiltink commented on internal/ebiten/sound.go
> +func (sc *SoundControl) SetVolume(group string, v float64) {
According to the documentation of `SoundControl` `SetVolume` should set the volume for all volume groups when an empty string has been provided. That case doesn't seem to be covered now.

2021-02-05 10:41 UTC, svenwiltink commented on internal/ebiten/asset.go
> +			context: audio.NewContext(44100),
Does this mean all assets must have 44100 as the sample rate? Does it break when the sound has a different sample rate?

2021-02-05 10:42 UTC, svenwiltink commented on internal/ebiten/sound.go
> +	s.player, _ = audio.NewPlayer(
spotted an ignored error ;)

2021-02-05 10:43 UTC, svenwiltink commented on internal/common/sound.go
> +	Options [][]byte
Options are the different variants of a sound?

2021-02-06 17:32 UTC, zacharyburkett commented on internal/ebiten/asset.go
> +			context: audio.NewContext(44100),
Yes, Ebiten only supports a single audio context with a single sample rate. Ebiten also suggests only using 44100 or 48000 for the sample rate for cross-platform consistency. I think enforcing 44100 for now is fine. Adding a configurable option in the future is doable.

2021-02-06 17:50 UTC, svenwiltink approved these changes

2021-02-06 17:50 UTC, merged